# Generated by Django 6.0 on 2025-12-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_star_points'),
        ('users', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='star',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='star',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awarded_stars', to='events.event'),
        ),
        migrations.AddField(
            model_name='star',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='star',
            name='giver',
        ),
    ]
