# Generated by Django 4.2 on 2026-01-25 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_city_event_event_type_event_hobbies_related_and_more'),
        ('users', '0004_profile_hobbies_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together={('giver', 'receiver', 'event')},
        ),
    ]
