# Generated by Django 4.2.7 on 2026-01-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_city_event_event_type_event_hobbies_related_and_more'),
        ('users', '0006_create_permanent_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_stars', to='events.event'),
        ),
    ]
