# Generated by Django 6.0 on 2025-12-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='star_points',
            field=models.PositiveIntegerField(default=0, help_text='Stars awarded to participants upon joining'),
        ),
    ]
