# Generated by Django 4.2.7 on 2026-02-03 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatroom_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='typing_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='typing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_in_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
