# Generated by Django 4.2.7 on 2026-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('star', 'Star'), ('event_join', 'Event Join'), ('event_reminder', 'Event Reminder'), ('message', 'Message'), ('follow', 'Follow')], max_length=20),
        ),
    ]
